name: Solar System Workflow

on:
  push:
    branches:
      - main
      - 'Feature/*'

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: 'superuser'
  MONGO_PASSWORD: 'SuperPassword'

jobs:
  unit-testing:
    name: Unit Testing
    strategy:
      matrix:
        nodejs_version: [18, 19, 20]
        operating_system: [ubuntu-latest, macos-latest]

        exclude:
          - nodejs_version: 20
            operating_system: macos-latest
    runs-on: ${{ matrix.operating_system }}
    steps:
      - name: Checkout and Setup Node
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ matrix.nodejs_version }}

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run Unit Tests
        uses: ./.github/actions/run-unit-tests

  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Check Code Coverage
        uses: ./.github/actions/check-code-coverage

  docker:
    name: Containerization
    needs: [code-coverage, unit-testing]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Build and Push (test)
        uses: ./.github/actions/docker-build-push
        with:
          push: false

      - name: Docker Build and Push (final)
        uses: ./.github/actions/docker-build-push
        with:
          push: true
